engine:
  name: terragrunt
  version: 0.83.0
dirs:
  "**/terragrunt.hcl":
    when_modified:
      file_patterns: ['${DIR}/terragrunt.hcl']
  '.':
    when_modified:
      file_patterns: []
automerge:
  enabled: true
  delete_branch: true
  require_explicit_apply: true
hooks:
  plan:
    pre:
      - type: env
        name: TG_PROVIDER_CACHE
        cmd: ['echo', '1']